### ISSUE TITLE
Not Working on M1

### ISSUE THREAD

**Issue by phyesix** [iSapozhnik/Pasty#6]
I'm trying on Apple M1 Pro but the app can't start.

macOS Ventura 13.5.2

**Comment by iSapozhnik** [comment]
Hey!
Did you figure out what was the issue?

**Comment by phyesix** [comment]
It's fixed in a way I don't understand. I actually restarted the Mac when I installed it, but after the 2nd or 3rd restart, it started working. 

In short, I don't know.  😂
